name: Restore RDS snapshot GitHub Action
description: This is a github actions to restore RDS snapshot

author: Saurabh Jambhule

branding:
  color: green
  icon: airplay

inputs:
  source:
    description: The identifier for the source DB snapshot
  target:
    description: The identifier for the target DB
  delete:
    description: Whether to delete target DB if exists
  cluster:
    description: Whether its a DB cluster or not
  sg:
    description: A list of Amazon EC2 VPC security groups to associate with this DB
  az:
    description: The Availability Zone where the database will be created
  subnet:
    description: A DB subnet group to associate with this DB
  tags:
    description: Tags to assign to the DB
  share:
    description: Whether to share an DB snapshot with another account
  assume:
    description: IAM role to be assumed for sharing DB
  key:
    description: The Amazon Web Services KMS key identifier for an encrypted DB snapshot
  account:
    description: Id of the target AWS account

outputs:
  success:
    description: Whether action was successful or not

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source }}
    - ${{ inputs.target }}
    - ${{ inputs.delete }}
    - ${{ inputs.cluster }}
    - ${{ inputs.sg }}
    - ${{ inputs.az }}
    - ${{ inputs.subnet }}
    - ${{ inputs.tags }}
    - ${{ inputs.share }}
    - ${{ inputs.assume }}
    - ${{ inputs.key }}
    - ${{ inputs.account }}
